---
- name: Set timezone
  become: yes
  timezone:
    name={{ timezone }}

- name: Install Development Pacakages
  become: yes
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - name: "@Development tools"
    - name: openssl-devel
    - name: bzip2-devel
    - name: readline-devel
    - name: sqlite-devel
