---
- stat: path=/home/vagrant/.anyenv
  register: anyenvdir
- name: Install Anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: /home/vagrant/.anyenv
  when: not anyenvdir.stat.exists

- name: Add Anyenv Settings into .bash_profile
  blockinfile:
    path: /home/vagrant/.bash_profile
    block: |
      export PATH="$HOME/.anyenv/bin:$PATH"
      eval "$(anyenv init -)"

- name: Reload .bash_profile
  shell: exec $SHELL -l
