---
- name: Install anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: /home/vagrant/.anyenv

- name: Add ~/.anyenv/bin to PATH
  lineinfile:
    dest: "/home/vagrant/.bashrc"
    line: "export PATH=$HOME/.anyenv/bin:$PATH"

- name: Eval anyenv init in ~/.bashrc
  lineinfile:
    dest: "/home/vagrant/.bashrc"
    line: 'eval "$(anyenv init -)"'

- name: Reload ~/.bashrc
  shell: "exec $SHELL -l"
